# Generated by Django 5.0.7 on 2024-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_secret',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
