# Generated by Django 5.0.7 on 2024-08-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_email'),
    ]

    operations = [
    ]
