# Generated by Django 5.0.7 on 2024-08-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouselogproduct',
            name='order',
        ),
    ]
