# Generated by Django 5.0.7 on 2024-08-16 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_warehouselogproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse_log_product',
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouselogproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_log', to='myapp.order'),
        ),
    ]
