# Generated by Django 5.0.7 on 2024-08-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
