# Generated by Django 5.0.7 on 2024-08-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_order_delivery_note_order_pickup_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_note',
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='PickupNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_notes', to='myapp.order')),
            ],
        ),
    ]
