# Generated by Django 5.0.7 on 2024-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_order_delivery_note_remove_order_pickup_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='cvv',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ifsc_code',
            field=models.CharField(default='DEFAULT_IFSC_CODE', max_length=11),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_process', 'Under Process'), ('pending', 'Pending')], default='submitted', max_length=20),
        ),
    ]
