# Generated by Django 5.0.7 on 2024-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_userdetails_cvv_userdetails_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
    ]
