# Generated by Django 5.0.7 on 2024-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_userdetails_ifsc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
    ]
