# Generated by Django 5.0.7 on 2024-09-14 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_userdetails_ifsc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('account_address', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_card', models.CharField(max_length=12, unique=True)),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to='aadhar_photos/')),
                ('pan_card', models.CharField(max_length=10, unique=True)),
                ('pan_photo', models.ImageField(blank=True, null=True, upload_to='pan_photos/')),
                ('driving_license_number', models.CharField(blank=True, max_length=15, null=True)),
                ('driving_license_photo', models.ImageField(blank=True, null=True, upload_to='driving_license_photos/')),
                ('primary_address', models.TextField()),
                ('secondary_address', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_process', 'Under Process'), ('pending', 'Pending')], default='submitted', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
