# Generated by Django 5.0.7 on 2024-09-18 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_accountdetail_userdetail_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Media_File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_file', models.ImageField(upload_to='media_files/')),
                ('name', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='myapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=50)),
                ('task_description', models.TextField()),
                ('task_title', models.CharField(max_length=100)),
                ('media_files', models.ManyToManyField(related_name='tasks', to='myapp.order_media_file')),
            ],
        ),
    ]
