# Generated by Django 5.0.7 on 2024-09-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_order_media_file_order_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_media_file',
            name='media_file',
            field=models.ImageField(blank=True, null=True, upload_to='media_files/'),
        ),
    ]
